var title = 'project1';
var screens = "Прстые, Сложные, Интерактивные";
var screenPrice = 135;
var rollback = 13;
var fullPrice = 135345;
var adaptive = true;
console.log(title, fullPrice, adaptive);
console.log(screens.length);
console.log("Стоимость верстки экранов: "+ screenPrice  + "Стоимость разработки сайта: "+ fullPrice);
console.log(screens.toLocaleLowerCase().split());
console.log(Math.trunc(fullPrice * (rollback/100)));